### ISSUE TITLE
Add software layer to handle telecommands (TC) and telemetries (TM)

### ISSUE THREAD

**Issue by lautaromendieta** [spacebee-technologies/rovertito-engineering-model#4]
# Tasks
- [x] Add documentation for network protocol stack and interaction patterns
- [x] Use Zephyr socket API to send and receive UDP datagrams
- [x] Implement an application layer over UDP
- [ ] Implement the interaction patterns in which the application layer messages are exchanged
